### PR TITLE
Version includes API calls and NLU analysis

### PR DESCRIPTION
**Pull request by taylorj8**

### CODE REVIEW

**Comment by HazelHilbert** [comment]
image
I am having problems with importing Cloudant. Do I have to download anything?

**Comment by yvah** [comment]
Hi! Daniel and I are in the glassrooms, you can join us.
For the issue, did you download ibmcloudant using pip? Looks like it lacks this module.

**Comment by HazelHilbert** [comment]
Unfortunately I am actually in a lecture haha

**Comment by HazelHilbert** [comment]
I'm also getting this error:
image
Sorry for all the questions, just trying to see if the NLU will still work. We should also make sure we are keeping track of all the imports and keys we need to run the code

**Comment by yvah** [comment]
IBM credentials might have changed if someone of the team reseted them, but it seems like you just don’t have the file with them. Try to reinstall cloudant using pip:
pip uninstall cloudant
pip install cloudant

**Comment by HazelHilbert** [comment]
I did that but it is giving the same error :/

**Comment by yvah** [comment]
So you checked the credentials file in the directory where it’s trying to find it?
You can also pass that error with exception. Generally not the best thing to do, but might help.

**Comment by HazelHilbert** [comment]
I don’t think I fully really understand what you mean. I installed cloudant through pip, but then just tried to run it. I don't have any file named "credentials.json" in my local directory. Are there some other steps I should do before running the code? Like do I have to download anything else or edit anything?

**Comment by HazelHilbert** [comment]
If it's easier, I could just try to sort it out tomorrow when we meet in person

**Comment by yvah** [comment]
Sorry for being confusing. It looks like the program doesn’t see credentials file. Add it to that directory:

**Comment by HazelHilbert** [comment]
Oh ok, how do I do that? 😅 Do I do it from IBM cloud?

**Comment by yvah** [comment]
No, just locally on your laptop directory. Go to the directory you see in
the traceback.

**Review by HazelHilbert — APPROVED** [review]
Sorry for the confusion! Everything looks good, nlu works :)

**Pull request merged**
